//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace menu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedore
    {
        public int ProveedorID { get; set; }
        public string NombreProveedor { get; set; }
        public string Telefono { get; set; }
        public string CorreoElectronico { get; set; }
    }
}
